[theme]
primaryColor = "#0073AE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#0F2436"
font = "sans serif"

[server]
fileWatcherType = "none"
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[global]
developmentMode = false
logLevel = "info"